---
title: "Bilans des scores CAPL"
author: "Pierre-Yves de Müllenheim"
date: "`r Sys.Date()`"
output:
  word_document:
    reference_docx: style.docx
---
  
```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
```

```{r load_packages}
library(dplyr)
library(glue)
library(flextable)
library(forcats)
library(officer)
library(skimr)
library(tidyr)
library(readr)
```

```{r import_data}
capl_res <- read_csv2("out/capl_results.csv")
```

```{r select_data}
capl_res_selection <-
  capl_res |> 
  select(
    gender,
    ecole,
    pc_score,
    plank_score,
    pacer_score,
    camsa_score,
    db_score,
    step_score,
    self_report_pa_score,
    mc_score,
    intrinsic_motivation_score,
    pa_competence_score,
    predilection_score,
    adequacy_score,
    ku_score,
    pa_guideline_score,
    crf_means_score,
    ms_means_score,
    sports_skill_score,
    fill_in_the_blanks_score,
    capl_score
  ) |>
  drop_na()
```

```{r get_stats_for_all_students}
capl_stats_all <-
  capl_res_selection |>
  skim() |>
  yank("numeric") |>
  mutate(
    mean_round = format(round(mean, 1), nsmall = 1),
    sd_round = format(round(sd, 1), nsmall = 1) |> trimws(),
    all = glue("{mean_round} ({sd_round})"),
  ) |>
  select(skim_variable, all) |>
  filter(
    skim_variable %in% c(
      "pc_score",
      "plank_score",
      "pacer_score",
      "camsa_score",
      "db_score",
      "step_score",
      "self_report_pa_score",
      "mc_score",
      "intrinsic_motivation_score",
      "pa_competence_score",
      "predilection_score",
      "adequacy_score",
      "ku_score",
      "pa_guideline_score",
      "crf_means_score",
      "ms_means_score",
      "sports_skill_score",
      "fill_in_the_blanks_score",
      "capl_score"
    )
  ) |>
  mutate(
    skim_variable = as.factor(skim_variable),
    skim_variable = fct_relevel(
      skim_variable,
      "pc_score",
      "plank_score",
      "pacer_score",
      "camsa_score",
      "db_score",
      "step_score",
      "self_report_pa_score",
      "mc_score",
      "intrinsic_motivation_score",
      "pa_competence_score",
      "predilection_score",
      "adequacy_score",
      "ku_score",
      "pa_guideline_score",
      "crf_means_score",
      "ms_means_score",
      "sports_skill_score",
      "fill_in_the_blanks_score",
      "capl_score"
    ),
    skim_variable = fct_recode(
      skim_variable,
      "Score PC (0 – 30)" = "pc_score",
      "Planche abdominale (0 – 10)" = "plank_score",
      "PACER (0 – 10)" = "pacer_score",
      "CAMSA (0 – 10)" = "camsa_score",
      "Score DB (0 – 30)" = "db_score",
      "Nombre de pas (0 – 25)" = "step_score",
      "AP auto-rapportée (0 – 5)" = "self_report_pa_score",
      "Score MC (0 – 30)" = "mc_score",
      "Motiv. Intr. (0 – 7,5)" = "intrinsic_motivation_score",
      "Compétence d’AP (0 – 7,5)" = "pa_competence_score",
      "Score de prédilection (0 – 7,5)" = "predilection_score",
      "Score d’aptitude (0 – 7,5)" = "adequacy_score",
      "Score KU (0 – 10)" = "ku_score",
      "Recommandations (0 - 1)" = "pa_guideline_score",
      "Fct. Cardio-respi (0 - 1)" = "crf_means_score",
      "Fct. Musculaire (0 - 1)" = "ms_means_score",
      "Entraîner ses habilités (0 - 1)" = "sports_skill_score",
      "Texte à trou (0 – 6)" = "fill_in_the_blanks_score",
      "Score total de LP (0 – 100)" = "capl_score"
    )
  ) |> 
  as_tibble()
```

```{r  get_stats_for_all_students_by_sex}
capl_stats_all_by_sex <-
  capl_res_selection |>
  group_by(gender) |> 
  skim() |>
  yank("numeric") |>
  mutate(
    mean_round = format(round(mean, 1), nsmall = 1),
    sd_round = format(round(sd, 1), nsmall = 1) |> trimws(),
    stats = glue("{mean_round} ({sd_round})"),
  ) |>
  select(skim_variable, gender, stats) |>
  filter(
    skim_variable %in% c(
      "pc_score",
      "plank_score",
      "pacer_score",
      "camsa_score",
      "db_score",
      "step_score",
      "self_report_pa_score",
      "mc_score",
      "intrinsic_motivation_score",
      "pa_competence_score",
      "predilection_score",
      "adequacy_score",
      "ku_score",
      "pa_guideline_score",
      "crf_means_score",
      "ms_means_score",
      "sports_skill_score",
      "fill_in_the_blanks_score",
      "capl_score"
    )
  ) |>
  mutate(
    skim_variable = as.factor(skim_variable),
    skim_variable = fct_relevel(
      skim_variable,
      "pc_score",
      "plank_score",
      "pacer_score",
      "camsa_score",
      "db_score",
      "step_score",
      "self_report_pa_score",
      "mc_score",
      "intrinsic_motivation_score",
      "pa_competence_score",
      "predilection_score",
      "adequacy_score",
      "ku_score",
      "pa_guideline_score",
      "crf_means_score",
      "ms_means_score",
      "sports_skill_score",
      "fill_in_the_blanks_score",
      "capl_score"
    ),
    skim_variable = fct_recode(
      skim_variable,
      "Score PC (0 – 30)" = "pc_score",
      "Planche abdominale (0 – 10)" = "plank_score",
      "PACER (0 – 10)" = "pacer_score",
      "CAMSA (0 – 10)" = "camsa_score",
      "Score DB (0 – 30)" = "db_score",
      "Nombre de pas (0 – 25)" = "step_score",
      "AP auto-rapportée (0 – 5)" = "self_report_pa_score",
      "Score MC (0 – 30)" = "mc_score",
      "Motiv. Intr. (0 – 7,5)" = "intrinsic_motivation_score",
      "Compétence d’AP (0 – 7,5)" = "pa_competence_score",
      "Score de prédilection (0 – 7,5)" = "predilection_score",
      "Score d’aptitude (0 – 7,5)" = "adequacy_score",
      "Score KU (0 – 10)" = "ku_score",
      "Recommandations (0 - 1)" = "pa_guideline_score",
      "Fct. Cardio-respi (0 - 1)" = "crf_means_score",
      "Fct. Musculaire (0 - 1)" = "ms_means_score",
      "Entraîner ses habilités (0 - 1)" = "sports_skill_score",
      "Texte à trou (0 – 6)" = "fill_in_the_blanks_score",
      "Score total de LP (0 – 100)" = "capl_score"
    )
  ) |> 
  pivot_wider(names_from = gender, names_glue = "all_{gender}", values_from = stats)
```

```{r  gets_stats_for_all_students_by_school}
capl_stats_all_by_school <-
  capl_res_selection |>
  group_by(ecole) |> 
  skim() |>
  yank("numeric") |>
  mutate(
    mean_round = format(round(mean, 1), nsmall = 1),
    sd_round = format(round(sd, 1), nsmall = 1) |> trimws(),
    stats = glue("{mean_round} ({sd_round})"),
  ) |>
  select(skim_variable, ecole, stats) |>
  filter(
    skim_variable %in% c(
      "pc_score",
      "plank_score",
      "pacer_score",
      "camsa_score",
      "db_score",
      "step_score",
      "self_report_pa_score",
      "mc_score",
      "intrinsic_motivation_score",
      "pa_competence_score",
      "predilection_score",
      "adequacy_score",
      "ku_score",
      "pa_guideline_score",
      "crf_means_score",
      "ms_means_score",
      "sports_skill_score",
      "fill_in_the_blanks_score",
      "capl_score"
    )
  ) |>
  mutate(
    skim_variable = as.factor(skim_variable),
    skim_variable = fct_relevel(
      skim_variable,
      "pc_score",
      "plank_score",
      "pacer_score",
      "camsa_score",
      "db_score",
      "step_score",
      "self_report_pa_score",
      "mc_score",
      "intrinsic_motivation_score",
      "pa_competence_score",
      "predilection_score",
      "adequacy_score",
      "ku_score",
      "pa_guideline_score",
      "crf_means_score",
      "ms_means_score",
      "sports_skill_score",
      "fill_in_the_blanks_score",
      "capl_score"
    ),
    skim_variable = fct_recode(
      skim_variable,
      "Score PC (0 – 30)" = "pc_score",
      "Planche abdominale (0 – 10)" = "plank_score",
      "PACER (0 – 10)" = "pacer_score",
      "CAMSA (0 – 10)" = "camsa_score",
      "Score DB (0 – 30)" = "db_score",
      "Nombre de pas (0 – 25)" = "step_score",
      "AP auto-rapportée (0 – 5)" = "self_report_pa_score",
      "Score MC (0 – 30)" = "mc_score",
      "Motiv. Intr. (0 – 7,5)" = "intrinsic_motivation_score",
      "Compétence d’AP (0 – 7,5)" = "pa_competence_score",
      "Score de prédilection (0 – 7,5)" = "predilection_score",
      "Score d’aptitude (0 – 7,5)" = "adequacy_score",
      "Score KU (0 – 10)" = "ku_score",
      "Recommandations (0 - 1)" = "pa_guideline_score",
      "Fct. Cardio-respi (0 - 1)" = "crf_means_score",
      "Fct. Musculaire (0 - 1)" = "ms_means_score",
      "Entraîner ses habilités (0 - 1)" = "sports_skill_score",
      "Texte à trou (0 – 6)" = "fill_in_the_blanks_score",
      "Score total de LP (0 – 100)" = "capl_score"
    )
  ) |> 
  pivot_wider(names_from = ecole, values_from = stats)
```

```{r get_stats_for_all_students_by_school_and_sex}
capl_stats_all_by_school_sex <-
  capl_res_selection |>
  group_by(ecole, gender) |> 
  skim() |>
  yank("numeric") |>
  mutate(
    mean_round = format(round(mean, 1), nsmall = 1),
    sd_round = format(round(sd, 1), nsmall = 1) |> trimws(),
    stats = glue("{mean_round} ({sd_round})"),
  ) |>
  select(skim_variable, ecole, gender, stats) |>
  filter(
    skim_variable %in% c(
      "pc_score",
      "plank_score",
      "pacer_score",
      "camsa_score",
      "db_score",
      "step_score",
      "self_report_pa_score",
      "mc_score",
      "intrinsic_motivation_score",
      "pa_competence_score",
      "predilection_score",
      "adequacy_score",
      "ku_score",
      "pa_guideline_score",
      "crf_means_score",
      "ms_means_score",
      "sports_skill_score",
      "fill_in_the_blanks_score",
      "capl_score"
    )
  ) |>
  mutate(
    skim_variable = as.factor(skim_variable),
    skim_variable = fct_relevel(
      skim_variable,
      "pc_score",
      "plank_score",
      "pacer_score",
      "camsa_score",
      "db_score",
      "step_score",
      "self_report_pa_score",
      "mc_score",
      "intrinsic_motivation_score",
      "pa_competence_score",
      "predilection_score",
      "adequacy_score",
      "ku_score",
      "pa_guideline_score",
      "crf_means_score",
      "ms_means_score",
      "sports_skill_score",
      "fill_in_the_blanks_score",
      "capl_score"
    ),
    skim_variable = fct_recode(
      skim_variable,
      "Score PC (0 – 30)" = "pc_score",
      "Planche abdominale (0 – 10)" = "plank_score",
      "PACER (0 – 10)" = "pacer_score",
      "CAMSA (0 – 10)" = "camsa_score",
      "Score DB (0 – 30)" = "db_score",
      "Nombre de pas (0 – 25)" = "step_score",
      "AP auto-rapportée (0 – 5)" = "self_report_pa_score",
      "Score MC (0 – 30)" = "mc_score",
      "Motiv. Intr. (0 – 7,5)" = "intrinsic_motivation_score",
      "Compétence d’AP (0 – 7,5)" = "pa_competence_score",
      "Score de prédilection (0 – 7,5)" = "predilection_score",
      "Score d’aptitude (0 – 7,5)" = "adequacy_score",
      "Score KU (0 – 10)" = "ku_score",
      "Recommandations (0 - 1)" = "pa_guideline_score",
      "Fct. Cardio-respi (0 - 1)" = "crf_means_score",
      "Fct. Musculaire (0 - 1)" = "ms_means_score",
      "Entraîner ses habilités (0 - 1)" = "sports_skill_score",
      "Texte à trou (0 – 6)" = "fill_in_the_blanks_score",
      "Score total de LP (0 – 100)" = "capl_score"
    )
  ) |> 
  pivot_wider(names_from = c(ecole, gender), names_glue = "{ecole}_{gender}", values_from = stats)
```

```{r join_stats}
capl_stats_general <-
  capl_stats_all |>
  left_join(capl_stats_all_by_sex) |>
  left_join(capl_stats_all_by_school) |>
  left_join(capl_stats_all_by_school_sex) %>%
  select(sort(names(.))) |>
  select(skim_variable, all, all_girl, all_boy, everything()) |> 
  rename(
    "Aérodrome" = AERODROME,
    "Jean-Piaget" = "JEAN PIAGET",
    "Notre-Dame de L'Azedière" = "NOTRE DAME DE L ADEZIERE",
    "Saint-Exupéry" = "SAINT EXUPERY",
    "Sainte-Colombe" = "SAINTE COLOMBE"
  )
```

```{r get_numbers_of_students}
# ALL
n_all <- glue("T ({nrow(capl_res_selection)})")
n_all_boy <- glue("G ({nrow(capl_res_selection |> filter(gender == 'boy'))})")
n_all_girl <- glue("F ({nrow(capl_res_selection |> filter(gender == 'girl'))})")

# AERODROME
n_all_aerodrome <- glue("T ({nrow(capl_res_selection |> filter(ecole == 'AERODROME'))})")
n_all_aerodrome_boy <- glue("G ({nrow(capl_res_selection |> filter(ecole == 'AERODROME' & gender == 'boy'))})")
n_all_aerodrome_girl <- glue("F ({nrow(capl_res_selection |> filter(ecole == 'AERODROME' & gender == 'girl'))})")

# JEAN PIAGET
n_all_jp <- glue("T ({nrow(capl_res_selection |> filter(ecole == 'JEAN PIAGET'))})")
n_all_jp_boy <- glue("G ({nrow(capl_res_selection |> filter(ecole == 'JEAN PIAGET' & gender == 'boy'))})")
n_all_jp_girl <- glue("F ({nrow(capl_res_selection |> filter(ecole == 'JEAN PIAGET' & gender == 'girl'))})")

# NOTRE DAME DE L'ADEZIERE
n_all_ndl <- glue("T ({nrow(capl_res_selection |> filter(ecole == 'NOTRE DAME DE L ADEZIERE'))})")
n_all_ndl_boy <- glue("G ({nrow(capl_res_selection |> filter(ecole == 'NOTRE DAME DE L ADEZIERE' & gender == 'boy'))})")
n_all_ndl_girl <- glue("F ({nrow(capl_res_selection |> filter(ecole == 'NOTRE DAME DE L ADEZIERE' & gender == 'girl'))})")

# SAINT-EXUPERY
n_all_stexp <- glue("T ({nrow(capl_res_selection |> filter(ecole == 'SAINT EXUPERY'))})")
n_all_stexp_boy <- glue("G ({nrow(capl_res_selection |> filter(ecole == 'SAINT EXUPERY' & gender == 'boy'))})")
n_all_stexp_girl <- glue("F ({nrow(capl_res_selection |> filter(ecole == 'SAINT EXUPERY' & gender == 'girl'))})")

# SAINTE COLOMBE
n_all_stcol <- glue("T ({nrow(capl_res_selection |> filter(ecole == 'SAINTE COLOMBE'))})")
n_all_stcol_boy <- glue("G ({nrow(capl_res_selection |> filter(ecole == 'SAINTE COLOMBE' & gender == 'boy'))})")
n_all_stcol_girl <- glue("F ({nrow(capl_res_selection |> filter(ecole == 'SAINTE COLOMBE' & gender == 'girl'))})")
```

```{r set_flex_table_func}
FitFlextableToPage <- function(ft, pgwidth = 6){

  ft_out <- ft %>% autofit()

  ft_out <- width(ft_out, width = dim(ft_out)$widths*pgwidth /(flextable_dim(ft_out)$widths))
  return(ft_out)
}
```

```{r make_table}
std_border <- fp_border(color = "black")

capl_stats_general |>
  mutate(
    id = c(2:5, 7:9,  11:15, 17:22, 24),
    skim_variable = fct_recode(
      skim_variable,
      "Score domaine (0 - 30)" = "Score PC (0 – 30)",
      "Score domaine (0 - 30)" = "Score DB (0 – 30)",
      "Score domaine (0 - 30)" = "Score MC (0 – 30)",
      "Score domaine (0 - 10)" = "Score KU (0 – 10)"
    )
  ) |>
  rename(" " = skim_variable) |>
  add_row(` ` = "PC", id = 1) |>
  add_row(` ` = "DB", id = 6) |>
  add_row(` ` = "MC", id = 10) |>
  add_row(` ` = "KU", id = 16) |>
  add_row(` ` = "CAPL", id = 23) |>
  arrange(id) |>
  select(-id) |>
  flextable() |>
  add_header_row(
    values = c(
      "",
      "Général",
      names(capl_stats_general)[5],
      names(capl_stats_general)[8],
      names(capl_stats_general)[11],
      names(capl_stats_general)[14],
      names(capl_stats_general)[17]
    ),
    colwidths = c(1, rep(3, 6)),
    top = TRUE
  ) |>
  add_header_row(
    values = c(
      " ",
      n_all,
      n_all_girl,
      n_all_boy,
      n_all_aerodrome,
      n_all_aerodrome_girl,
      n_all_aerodrome_boy,
      n_all_jp,
      n_all_jp_girl,
      n_all_jp_boy,
      n_all_ndl,
      n_all_ndl_girl,
      n_all_ndl_boy,
      n_all_stexp,
      n_all_stexp_girl,
      n_all_stexp_boy,
      n_all_stcol,
      n_all_stcol_girl,
      n_all_stcol_boy
    ),
    colwidths = rep(1, 19),
    top = FALSE
  ) |> 
  delete_rows(i = 2, part = "header") |> 
  merge_at(i = 1, j = c(2:4), part = "header") |> 
  merge_at(i = 1, j = c(5:7), part = "header") |> 
  merge_at(i = 1, j = c(8:10), part = "header") |> 
  merge_at(i = 1, j = c(11:13), part = "header") |> 
  merge_at(i = 1, j = c(14:16), part = "header") |> 
  merge_at(i = 1, j = c(17:19), part = "header") |> 
  align(align = "center", j = c(2:19), part = "all") |> 
  width(j = 1, width = 2.4, unit = "cm") |> 
  width(j = 2:19, width = 1.4, unit = "cm") |> 
  merge_at(i = 1, j = c(1:19), part = "body") |> 
  merge_at(i = 6, j = c(1:19), part = "body") |> 
  merge_at(i = 10, j = c(1:19), part = "body") |> 
  merge_at(i = 16, j = c(1:19), part = "body") |> 
  merge_at(i = 23, j = c(1:19), part = "body") |> 
  bg(j = c(2:4, 8:10, 14:16), bg = "grey90", part = "all") |> 
  hline(i = c(1, 5, 6, 9, 10, 15, 16, 22, 23), part = "body", border = std_border) |> 
  bold(i = c(1, 2), bold = TRUE, part = "header") |> 
  bold(i = c(1, 6, 10, 16, 23), bold = TRUE, part = "body")
```


